# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - client/

variables:
  projectDirectory: "$(System.DefaultWorkingDirectory)/client"
  # Agent VM image name
  vmImageName: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Setup Environment"

  - script: npm install
    workingDirectory: "$(projectDirectory)"
    displayName: "Install Dependencies"

  - script: npm run build:ci
    workingDirectory: "$(projectDirectory)"
    displayName: "Build"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(projectDirectory)/www"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/www"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(projectDirectory)/deployment"
      TargetFolder: "$(Build.ArtifactStagingDirectory)/deployment"


  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"

