version: '3.9'

services:
   azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10001:10000"
      - "10002:10001"
      - "10003:10002"
    volumes:
      - c:/azurite:/workspace mcr.microsoft.com/azure-storage/azurite
